### ISSUE TITLE
Mix of string indicators break highlighting

### ISSUE THREAD

**Issue by solloc** [larshp/vscode-abap#1]
When I use an apostrophe within a string wrapped in pipes, the syntax highlighting breaks. See example below:

![2017-12-07 10_47_54-zcl_di_bod abap - ra-plm arbeitsbereich - visual studio code](https://user-images.githubusercontent.com/11792171/33708968-338d07d2-db3c-11e7-9b9c-6deb7d0ca5a3.png)

**Comment by larshp** [comment]
thanks

Think this is the same issue as https://github.com/pvl/abap.tmbundle/issues/5 

vscode-abap is based on abap.tmbundle

**Comment by solloc** [comment]
yes, definitely looks similar, didn't look into that repo.

**Comment by solloc** [comment]
oh... didn't want to close it

**Comment by larshp** [comment]
will probably be fixed with https://github.com/larshp/vscode-abap/pull/3

**Comment by FreHu** [comment]
Yep, you can close this.
