### ISSUE TITLE
Add indentation rules

### ISSUE THREAD

**Issue by FreHu** [larshp/vscode-abap#14]
The language configuration allows to configure places which introduce an indentation level:
https://code.visualstudio.com/api/language-extensions/language-configuration-guide

**Comment by larshp** [comment]
the abaplint vscode extension can do pretty printing with Shift+F1, plus it also does indentation

**Comment by FreHu** [comment]
This is a bit better because it indents/denidents as you type.

**Comment by larshp** [comment]
I use the old editor, so IF's end up as in the following screenshot when using the new editor

anyhow, good idea, I'll just disable `editor.autoIndent` 😁 

![image](https://user-images.githubusercontent.com/5888506/54487541-76172280-4897-11e9-8278-fbce8283d13e.png)

**Comment by larshp** [comment]
hmm, this is actually a bit difficult because there are some implicit dendentation

but I guess its okay to add for the eays ones, IF, METHOD etc.
