### ISSUE TITLE
autoclosing pairs issue

### ISSUE THREAD

**Issue by marcellourbani** [larshp/vscode-abap#29]
Since last update a very annoying autocomplete behaviour emerged:
![autoclose](https://user-images.githubusercontent.com/2453277/155096159-287a5b6d-0087-4e5e-b1ba-0991de6e5e73.gif)

This actually works fine if you type say IF. or METHOD., but you never do it without adding a condition or method name. Maybe makes sense with DO.ENDDO. but even then you can DO WHILE...
Tried changing it to {"open":"IF.","close":"ENDIF."} but it's the same

**Comment by larshp** [comment]
cool, saw this issue on Friday

I've disabled all autocomplete in my editors, so did not see this until now

**Comment by larshp** [comment]
merged

v0.5.7 published

**Comment by marcellourbani** [comment]
this was fast! thanks

**Comment by larshp** [comment]
ship it, ship it 😄
