### ISSUE TITLE
Pasting ABAP Code changes indentation

### ISSUE THREAD

**Issue by jkrwdf** [larshp/vscode-abap#33]
With the change available since yesterday (2024-MAY-12), I observe that when I paste code into Visual Studio Code with this extension enabled, then I get changed indentations. 

For example, I have a class file which starts with a bunch of deferred declarations like 

```
CLASS lcl_1 DEFINITION DEFERRED.
CLASS lcl_2 DEFINITION DEFERRED.
CLASS lcl_3 DEFINITION DEFERRED.
...
```

Since yesterday, the plugin changes the result of my paste to

```
CLASS lcl_1 DEFINITION DEFERRED.
  CLASS lcl_2 DEFINITION DEFERRED.
  CLASS lcl_3 DEFINITION DEFERRED.
  ...
```

Eventually a configuration option could be offered to prevent all kind of code change by the plug-in and restrict it to coloring?

**Comment by larshp** [comment]
hmm, it only included changes to folding, https://github.com/larshp/vscode-abap/commit/c5c36241f3bed7f11f1223ba71c8cf4b055024a6

**Comment by larshp** [comment]
tho https://github.com/larshp/vscode-abap/blame/main/language-configuration.json#L54 might need to be updated

**Comment by larshp** [comment]
I got the same behavior in the old version, you can try installing the old version under extension settings,

![image](https://github.com/larshp/vscode-abap/assets/5888506/88f0a8d2-c203-4fb5-994a-cdb9ff9ded24)

**Comment by jkrwdf** [comment]
Correct, with the old version I have the same behavior. 

When I opened the link to the configuration file I dimly remember that I had deleted this section in the configuration file to get rid of this indentation behavior, and it seems that by the update of the plug-in this manual change has been overwritten.

**Comment by jkrwdf** [comment]
I found my notes from the past... In fact I had deleted all content of the configuration file except the sections "comments" and "colorizedBracketPairs" in order to stop all code changes by the plug-in. 

Maybe the idea to make such read-only behavior configurable officially can be considered?

**Comment by larshp** [comment]
"CLASS lcl_1 DEFINITION DEFERRED" that is a bug, which can be fixed, pull requests welcome

read-only behavior: pull requests welcome, this is a language configuration file, not an extension with code, I dont know how to make this configurable

**Comment by jkrwdf** [comment]
Thanks for your assessment and the comments. 
I will close this issue.

**Comment by larshp** [comment]
I've opened https://github.com/larshp/vscode-abap/issues/34 for fixing the DEFINITION DEFERRED, its a bug
